spring.application.name=rent
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://fluvinu:fluvinu01@rentdb.yo1lip9.mongodb.net/rentdb}
spring.data.mongodb.database=rentdb

jwt.secret=${JWT_SECRET:94a08da1fecbb6e8b46990538c7b50b2b8d0033c4613c015b6082d46e3d23838}
jwt.expiration=86400000
